export interface ITransportMonthTotal{
  transportName: string,
  transportCode: number,
  waybillsCount: number,
  days: number,
  hours: number,
  earnings: number,
  weekend: number,
  bonus: number,
  factFuelConsumption: number,
  normalFuelConsumption: number,
  numberOfRuns: number,
  totalMileage: number,
  totalMileageWithLoad: number,
  transportedLoad: number,
  normShift: number,
  conditionalReferenceHectares: number,
}